### ISSUE TITLE
[docs] dynamically read chain list from latest registry instead of the registry package

### ISSUE THREAD

**Issue by avious00** [hyperlane-xyz/v3-docs#95]
- [Address](https://docs.hyperlane.xyz/docs/reference/contract-addresses) & [Domains](https://docs.hyperlane.xyz/docs/reference/domains) should reflect the updated registry
- Have the chain dropdown component (which I believe pulls from the AddressTable) e.g. in [Send Your First Message](https://docs.hyperlane.xyz/docs/your-first-message) & [Post-Dispatch Hooks](https://docs.hyperlane.xyz/docs/reference/hooks/overview) reflect the registry's chain list
```[tasklist]
### Tasks
- [ ] https://github.com/hyperlane-xyz/v3-docs/issues/174
```

**Comment by jmrossy** [comment]
@avious00 This was already partly done here: https://github.com/hyperlane-xyz/v3-docs/pull/79
But it uses the static info in the published registry instead of dynamically querying. We can make this dynamic but it would be more like 1 eng day instead of 0.5 and we should do https://github.com/hyperlane-xyz/hyperlane-registry/issues/42 first
